const SUBJECTS=[["Ética Profissional",82,44],["Direito Administrativo",71,36],["Direito Penal",68,30],["Processo Civil",74,27],["Constitucional",66,22],["Processo Penal",79,19],["Civil",73,24],["Trabalho",61,18],["Tributário",58,14]];
const FLASHCARDS=[
  ["Ética","Qual é a sanção disciplinar mais grave?","Exclusão, aplicada nas hipóteses legais mais severas dentro do regime disciplinar."],
  ["Administrativo","Quando a improbidade exige dolo?","Na sistemática atual, a responsabilização por improbidade depende de conduta dolosa."],
  ["Penal","Qual a diferença central entre roubo e extorsão?","Na extorsão, a participação da vítima é indispensável; no roubo, não."],
  ["Proc. Civil","Prazo geral dos recursos no CPC?","Em regra, 15 dias úteis, com exceção dos embargos de declaração."],
  ["Constitucional","Como revisar melhor?","Misture questões, erro comentado e repetição espaçada em blocos curtos."],
  ["Trabalho","Como usar o sistema?","Questões primeiro, revisão de erros depois, e flashcards para fixação."]
];
const QUESTIONS=[
  {subject:"Ética Profissional",text:"No contexto disciplinar da advocacia, qual medida representa a sanção mais grave dentro do Estatuto?",options:["Advertência","Suspensão","Exclusão","Censura"],answer:2,explanation:"Exclusão é a resposta esperada quando a pergunta cobra a sanção disciplinar mais grave."},
  {subject:"Direito Administrativo",text:"Em licitações, o pregão é voltado principalmente para qual tipo de contratação?",options:["Alienação de bens imóveis","Bens e serviços comuns","Trabalho técnico-artístico","Leilão de bens apreendidos"],answer:1,explanation:"Pregão é usado para bens e serviços comuns, inclusive serviços comuns de engenharia."},
  {subject:"Direito Penal",text:"Qual elemento diferencia a extorsão do roubo em muitas questões de prova?",options:["Uso de violência","Bem jurídico tutelado","Participação indispensável da vítima","Natureza da ação penal"],answer:2,explanation:"Na extorsão, a vítima precisa agir, tolerar ou deixar de agir para a vantagem indevida ocorrer."},
  {subject:"Processo Civil",text:"Qual é o prazo, em regra, para interposição da apelação?",options:["5 dias","10 dias","15 dias úteis","30 dias"],answer:2,explanation:"Apelação segue o prazo recursal geral de 15 dias úteis."}
];
const state={xp:3420,xpToday:240,level:12,correct:19,wrong:6,reviewQueue:7,answered:25,cardsSeen:41,focusMinutes:440,achievements:5,streak:8,questionIndex:0,timer:1500,running:false,interval:null};
const subjectGrid=document.getElementById('subjectGrid');
const flashcardGrid=document.getElementById('flashcardGrid');
const questionSubject=document.getElementById('questionSubject');
const questionText=document.getElementById('questionText');
const optionsBox=document.getElementById('options');
const feedbackBox=document.getElementById('feedbackBox');
const recommendation=document.getElementById('recommendation');
function renderSubjects(){subjectGrid.innerHTML=SUBJECTS.map(([name,accuracy,done])=>`<article class="subject-card"><div class="subject-head"><h4>${name}</h4><span class="pill">${accuracy>=75?'forte':accuracy>=65?'subindo':'revisar'}</span></div><div class="subject-meta"><span>${done} questões</span><span>${accuracy}% acerto</span></div><div class="progress"><span style="width:${accuracy}%"></span></div><div class="subject-actions"><button class="chip">Questões</button><button class="chip">Flashcards</button><button class="chip">Revisão</button></div></article>`).join('')}
function renderFlashcards(){flashcardGrid.innerHTML=FLASHCARDS.map((card,i)=>`<article class="flashcard"><small>${card[0]}</small><strong id="flash-title-${i}">${card[1]}</strong><p id="flash-text-${i}">Toque em revelar para ver a resposta resumida.</p><button class="chip" onclick="toggleFlashcard(${i})">Revelar</button></article>`).join('')}
window.toggleFlashcard=function(i){const title=document.getElementById(`flash-title-${i}`);const text=document.getElementById(`flash-text-${i}`);const card=FLASHCARDS[i];const showingBack=title.dataset.back==='true';if(showingBack){title.textContent=card[1];text.textContent='Toque em revelar para ver a resposta resumida.';title.dataset.back='false'}else{title.textContent='Resposta';text.textContent=card[2];title.dataset.back='true';state.cardsSeen+=1;updateStats()}}
function renderQuestion(){const q=QUESTIONS[state.questionIndex];questionSubject.textContent=q.subject;questionText.textContent=q.text;feedbackBox.textContent='Escolha uma alternativa para receber feedback imediato.';optionsBox.innerHTML=q.options.map((opt,idx)=>`<button class="option" data-index="${idx}">${String.fromCharCode(65+idx)}. ${opt}</button>`).join('');optionsBox.querySelectorAll('.option').forEach(btn=>btn.addEventListener('click',()=>answerQuestion(Number(btn.dataset.index))))}
function answerQuestion(index){const q=QUESTIONS[state.questionIndex];const buttons=[...optionsBox.querySelectorAll('.option')];buttons.forEach((btn,idx)=>{btn.disabled=true;if(idx===q.answer)btn.classList.add('correct');if(idx===index&&idx!==q.answer)btn.classList.add('wrong')});if(index===q.answer){state.correct+=1;state.xp+=40;state.xpToday+=40;feedbackBox.textContent=`Acertou. ${q.explanation}`}else{state.wrong+=1;state.reviewQueue+=1;state.xp+=10;state.xpToday+=10;feedbackBox.textContent=`Errou. ${q.explanation}`}state.answered+=1;updateStats();updateRecommendation()}
function nextQuestion(){state.questionIndex=(state.questionIndex+1)%QUESTIONS.length;renderQuestion();feedbackBox.textContent='Nova questão carregada.'}
function updateRecommendation(){const acc=Math.round((state.correct/Math.max(1,state.correct+state.wrong))*100);if(acc<70)recommendation.textContent='Seu próximo melhor passo é revisar erros recentes e depois refazer 5 questões.';else if(state.reviewQueue>=8)recommendation.textContent='Há muitos pontos para revisão: ataque a fila de erros antes do simulado completo.';else recommendation.textContent='Você está em bom ritmo: siga para mais um bloco de questões e finalize com flashcards.'}
function formatMinutes(total){const h=Math.floor(total/60),m=total%60;return`${String(h).padStart(2,'0')}h ${String(m).padStart(2,'0')}m`}
function updateStats(){const total=state.correct+state.wrong;const acc=Math.round((state.correct/Math.max(1,total))*100);document.getElementById('xpToday').textContent=state.xpToday;document.getElementById('streakValue').textContent=`${state.streak} dias`;document.getElementById('correctValue').textContent=state.correct;document.getElementById('wrongValue').textContent=state.wrong;document.getElementById('globalPercent').textContent=`${acc}%`;document.getElementById('globalBar').style.width=`${acc}%`;document.getElementById('totalAnswered').textContent=state.answered;document.getElementById('accuracyRate').textContent=`${acc}%`;document.getElementById('cardsSeen').textContent=state.cardsSeen;document.getElementById('focusTime').textContent=formatMinutes(state.focusMinutes);document.getElementById('xpTotal').textContent=state.xp;document.getElementById('levelValue').textContent=state.level;document.getElementById('reviewQueue').textContent=state.reviewQueue;document.getElementById('achievementCount').textContent=state.achievements}
function renderTimer(){const min=Math.floor(state.timer/60),sec=state.timer%60;document.getElementById('timerDisplay').textContent=`${String(min).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
function startTimer(){if(state.running)return;state.running=true;state.interval=setInterval(()=>{if(state.timer>0){state.timer-=1}else{clearInterval(state.interval);state.running=false;state.focusMinutes+=25;renderTimer();updateStats();return}renderTimer()},1000)}
function pauseTimer(){state.running=false;clearInterval(state.interval)}
function resetTimer(){pauseTimer();state.timer=1500;renderTimer()}
document.getElementById('nextQuestion').addEventListener('click',nextQuestion);
document.getElementById('markReviewed').addEventListener('click',()=>{state.reviewQueue+=1;feedbackBox.textContent='Questão enviada para revisão. Ótimo para atacar erros depois.';updateStats();updateRecommendation()});
document.getElementById('startTimer').addEventListener('click',startTimer);
document.getElementById('pauseTimer').addEventListener('click',pauseTimer);
document.getElementById('resetTimer').addEventListener('click',resetTimer);
const themeToggle=document.getElementById('themeToggle');const root=document.documentElement;themeToggle.addEventListener('click',()=>{root.setAttribute('data-theme',root.getAttribute('data-theme')==='dark'?'light':'dark')});
const menuButton=document.getElementById('menuButton');const sidebar=document.getElementById('sidebar');menuButton.addEventListener('click',()=>sidebar.classList.toggle('open'));
document.querySelectorAll('[data-nav]').forEach(button=>{button.addEventListener('click',()=>{document.querySelectorAll('[data-nav]').forEach(b=>b.classList.remove('active'));button.classList.add('active');const target=document.getElementById(button.dataset.nav);if(target)target.scrollIntoView({behavior:'smooth',block:'start'});sidebar.classList.remove('open')})});
const heroStart=document.getElementById('heroStart');if(heroStart){heroStart.addEventListener('click',e=>{e.preventDefault();document.getElementById('questoes').scrollIntoView({behavior:'smooth',block:'start'})})}
renderSubjects();renderFlashcards();renderQuestion();renderTimer();updateStats();updateRecommendation();
